docs/decisions/0002-initial-api-specification.rst
**Description:**
Defines a formal API spec for the subsidy application.
Note some remaining open questions in the first chapter of the doc.
**JIRA:**
https://2u-internal.atlassian.net/browse/ENT-6741
**Reviewers:**
**Merge checklist:**
=> docs: initial API spec draft

.github/workflows/ci.yml, docs/decisions/0002-initial-api-specification.rst, docs/decisions/0003-fulfillment-and-corrective-policies.rst
https://2u-internal.atlassian.net/browse/ENT-6743
=> docs: corrective policies for fulfillments ADR. ENT-6743

enterprise_subsidy/apps/api_client/base_oauth.py, enterprise_subsidy/apps/api_client/enterprise.py, enterprise_subsidy/apps/api_client/tests/test_enterprise.py, enterprise_subsidy/settings/base.py, enterprise_subsidy/settings/devstack.py, test_utils/utils.py
**Description:** Base oauth api client + enterprise api client for related functions
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-6838
**Dependencies:** dependencies on other outstanding PRs, issues, etc. 
**Merge checklist:**
**Post merge:**
finished.
**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.
=> feat: adding base and enterprise api clients

enterprise_subsidy/apps/api/v1/tests/test_views.py, enterprise_subsidy/apps/api_client/base_oauth.py, enterprise_subsidy/apps/api_client/enterprise_catalog.py, enterprise_subsidy/apps/api_client/tests/test_enterprise_catalog.py, enterprise_subsidy/apps/subsidy/constants.py, enterprise_subsidy/apps/subsidy/models.py
=> feat: connecting catalog client and finalizing price

enterprise_subsidy/apps/api/v1/decorators.py, enterprise_subsidy/apps/api/v1/tests/mixins.py, enterprise_subsidy/apps/api/v1/tests/test_views.py, enterprise_subsidy/apps/api/v1/urls.py, enterprise_subsidy/apps/api/v1/views/content_metadata.py, enterprise_subsidy/apps/api/v1/views/subsidy.py, enterprise_subsidy/apps/api/v1/views/transaction.py, enterprise_subsidy/apps/api_client/enterprise_catalog.py, enterprise_subsidy/apps/api_client/tests/test_enterprise_catalog.py, enterprise_subsidy/apps/subsidy/constants.py, enterprise_subsidy/apps/subsidy/rules.py, test_utils/utils.py
new metadata view in the subsidy v1 endpoints
=> feat: content metadata view to surface price and source data

enterprise_subsidy/settings/local.py
Adding service docker container name to local allowed hosts setting. Needed to test the subsidy service client locally again the subsidy service view
=> chore: adding service docker container to local allowed hosts

Makefile, enterprise_subsidy/apps/api/v1/views/content_metadata.py, enterprise_subsidy/apps/api/v1/views/transaction.py, enterprise_subsidy/apps/api_client/enterprise.py, enterprise_subsidy/apps/api_client/enterprise_catalog.py, enterprise_subsidy/apps/api_client/tests/test_enterprise.py, enterprise_subsidy/apps/subsidy/admin.py
=> fix: checkpoint - smooth the rough edges

enterprise_subsidy/apps/api_client/enterprise.py
=> feat: temporarily force cache miss for JWT reasons on bulk enroll call

docs/decisions/0005-subsidy-model-consolidation.rst
* rename ADR from 0004 -> 0005 to fix conflict
* fix typo
* use "subsidy_type" to refer to the type column
* change status to accepted
=> fix: ADR 0005 had various typos and was slightly incomplete

enterprise_subsidy/apps/api_client/enterprise_catalog.py
ENT-6990
https://2u-internal.atlassian.net/browse/ENT-6990
=> fix: catalog client now returns price as integer cents, not float cents.

Makefile, docker-compose.yml
- Breaking out some of the work in https://github.com/openedx/enterprise-subsidy/pull/51
- add some Makefile commands to bring up redis
- dont cache src so its easier to work on plugins
=> feat: redis makefile commands

enterprise_subsidy/apps/api/paginators.py, enterprise_subsidy/apps/api/v1/views/transaction.py, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Will make it easy to plug the aggregates pagination into other versions of transaction views.
=> refactor: extract transaction list aggregates into a shareable paginator class

enterprise_subsidy/apps/api/paginators.py, enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py, enterprise_subsidy/apps/api/v2/views/transaction.py
little follow-up from ENT-6937
=> feat: use aggregates paginator in v2 list views.

enterprise_subsidy/settings/base.py
https://github.com/crccheck/django-object-actions#quick-start-guide
=> fix: add django_object_actions to INSTALLED_APPS.

enterprise_subsidy/apps/api_client/enterprise.py, enterprise_subsidy/apps/transaction/admin.py, enterprise_subsidy/apps/transaction/apps.py, enterprise_subsidy/apps/transaction/signals/handlers.py, enterprise_subsidy/apps/transaction/tests/test_signal_handlers.py, enterprise_subsidy/apps/transaction/tests/test_views.py, enterprise_subsidy/apps/transaction/views.py, enterprise_subsidy/settings/base.py, enterprise_subsidy/templates/admin/unenroll.html, requirements/base.in, requirements/base.txt, requirements/dev.in, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
related PR : https://github.com/openedx/openedx-ledger/pull/21
Jira: https://2u-internal.atlassian.net/browse/ENT-6935
Create two transactions related to generated platform/enterprise enrollments, reverse one transaction, unenroll the other
=> feat: subsidy implementation of unenrollments

enterprise_subsidy/apps/api/v1/tests/test_views.py, enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py, enterprise_subsidy/apps/content_metadata/api.py, enterprise_subsidy/apps/fulfillment/api.py, enterprise_subsidy/apps/fulfillment/tests/__init__.py, enterprise_subsidy/apps/fulfillment/tests/test_api.py, enterprise_subsidy/apps/subsidy/models.py, enterprise_subsidy/apps/subsidy/tests/test_models.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
- Adds a fulfillment handler for GetSmarter Exec Ed fulfillment.
- https://2u-internal.atlassian.net/browse/ENT-6804
- https://2u-internal.atlassian.net/browse/ENT-6931
- https://2u-internal.atlassian.net/browse/ENT-7068
- https://2u-internal.atlassian.net/browse/ENT-7079
=> feat: geag fulfillment

enterprise_subsidy/apps/fulfillment/api.py, enterprise_subsidy/apps/subsidy/models.py, enterprise_subsidy/apps/subsidy/tests/test_models.py
- fix call to geag client
- if no price is available, its not redeemable
=> fix: no price, not redeemable

enterprise_subsidy/apps/fulfillment/api.py, enterprise_subsidy/apps/fulfillment/tests/test_api.py
=> fix: i like my uuids str'ed

enterprise_subsidy/apps/fulfillment/api.py, enterprise_subsidy/apps/fulfillment/tests/test_api.py
we'll pull this out later, probably, but trying to get a geag allocation to succeed.
=> fix: temp hack around geag allocation validation

enterprise_subsidy/apps/fulfillment/api.py
- transaction quantities are decrements in cents, geag needs positive dollar prices
=> fix: propelry convert prices for GEAG

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
- getsmarter-api-clients==0.5.3
=> feat: getsmarter-api-clients==0.5.3

enterprise_subsidy/apps/content_metadata/api.py, enterprise_subsidy/apps/content_metadata/tests/test_api.py, enterprise_subsidy/apps/subsidy/models.py
- Appropriate logging for the redemption flow.
- Add some unit tests around `price_for_content()`.
=> feat: add better logging to the redemption path. ENT-7133

README.rst, docker-compose.yml
- the readme has some outdated instructions
- the toolbar env config needed a syntax fix
=> fix: tweak init

Makefile, provision-enterprise-subsidy.sh
- a couple of additional tweaks to the cold-start
=> fix: init tweaks

enterprise_subsidy/settings/base.py, enterprise_subsidy/settings/utils.py, requirements/base.in, requirements/base.txt, requirements/ci.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
- add/configure https://github.com/dabapps/django-log-request-id middleware
- makes use of recent addition of `X-Request-ID` headers from SRE team
- adds `X-Request-ID` response header
Further testing will be required in stage - to ensure we're capturing the proper id. This is from devstack:
```
enterprise-subsidy.app | 2023-05-15 14:19:50,792 WARNING 42 [django.request] [user None] [ip None] [request_id e644a8ba99cd42b79956290e4b782913] log.py:224 - Not Found: /
enterprise-subsidy.app | 2023-05-15 14:19:50,792 WARNING 42 [django.request] [user None] [ip None] [request_id e644a8ba99cd42b79956290e4b782913] log.py:224 - Not Found: /
enterprise-subsidy.app | 2023-05-15 14:19:50,792 WARNING 42 [django.request] [user None] [ip None] [request_id e644a8ba99cd42b79956290e4b782913] log.py:224 - …
```
=> feat: enable x-request-id logging, replying

enterprise_subsidy/settings/utils.py
I needed to also edit the syslog formatter
=> feat: tweak request-id logging

enterprise_subsidy/settings/base.py, enterprise_subsidy/settings/utils.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
- https://github.com/dabapps/django-log-request-id
- https://devcenter.heroku.com/articles/http-request-id#usage-with-django
=> feat: x-request-id logging

requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
Runs `make upgrade` to pull in https://github.com/openedx/openedx-ledger/pull/27
=> chore: run make upgrade to pull in openedx-ledger==1.0.0

enterprise_subsidy/apps/subsidy/admin.py, enterprise_subsidy/settings/devstack.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
* Integrates changes from https://github.com/openedx/openedx-ledger/pull/29
* Updates Subsidy admin detail to show current and starting balances in human-readable form
* Sets some basic search/list filter fields for Subsidy list view.
* Sets sane readonly fields and fixes bug that checks for override.
Note you can set the `ALLOW_LEDGER_MODIFICATION` setting to True in `private.py` (local development) or via edx-internal to make _all_ fields of the Subsidy model editable in django admin.
=> feat: django admin quality of life stuff

docs/decisions/0007-handling-learner-initiated-unenrollments.rst, enterprise_subsidy/apps/api_client/enterprise.py, enterprise_subsidy/apps/api_client/tests/test_enterprise.py, enterprise_subsidy/apps/transaction/management/__init__.py, enterprise_subsidy/apps/transaction/management/commands/__init__.py, enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py, enterprise_subsidy/apps/transaction/tests/test_management.py, enterprise_subsidy/apps/transaction/utils.py
learner initiated unenrollment monitoring
=> feat: learner initiated unenrollment monitoring

docs/decisions/0008-idempotency-keys.rst
[preview ADR](https://github.com/openedx/enterprise-subsidy/blob/9698172a3a630134a191fe577dade97363856756/docs/decisions/0008-idempotency-keys.rst)
ENT-6865
=> docs: Add ADR describing idempotency keys

enterprise_subsidy/apps/api_client/enterprise.py
Log more info when enroll call fails.
=> feat: log enroll error response payloads

enterprise_subsidy/apps/fulfillment/api.py, enterprise_subsidy/apps/fulfillment/exceptions.py, enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py, enterprise_subsidy/apps/transaction/tests/test_management.py, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
- gated behind a new setting `ENTERPRISE_SUBSIDY_AUTOMATIC_EXTERNAL_CANCELLATION` (for now)
- added tests
- will deploy out to stage and test LIVE ✨
=> feat: automatic geag cancellation on unenroll

enterprise_subsidy/apps/subsidy/models.py
This PR adds ordering for the Subsidy model
###JIRA: [ENT-7445](https://2u-internal.atlassian.net/browse/ENT-7445)
=> feat: ENT-7445 Added ordering for the Subsidy model

.annotation_safe_list.yml, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/production.txt, requirements/quality.txt, requirements/test.txt, requirements/validation.txt
https://github.com/openedx/openedx-ledger/releases/tag/1.2.0
Adds the ability to credit (or debit) manually from a ledger via an Adjustment model, outside the context of a redemption/enrollment, in the event of dispute or confusion.
=> feat: openedx-ledger 1.2.0 | Adds Adjustment model.

provision-enterprise-subsidy.sh
- noticed some fixes leftover from the mysql8 upgrade
- [make the script safer](https://sipb.mit.edu/doc/safe-shell/)
- properly set colors
=> fix: mysql8 provisioning scripts

.github/workflows/upgrade-python-requirements.yml
=> chore: Variables need quotes in github actions.

enterprise_subsidy/apps/transaction/management/commands/backpopulate_transaction_parent_content_key.py, enterprise_subsidy/apps/transaction/tests/test_management.py
=> feat: add tool to backpopulate parent_content_key

enterprise_subsidy/apps/transaction/management/commands/backpopulate_transaction_parent_content_key.py, enterprise_subsidy/apps/transaction/tests/test_management.py
=> fix: use catalog-agnostic endpoint for fetching content metdata

.gitignore, Makefile
Adds `dev.backup` and `dev.restore` makefile targets.
=> build: dev backup and restore commands

enterprise_subsidy/apps/api_client/enterprise.py, enterprise_subsidy/apps/api_client/tests/test_enterprise.py
This change respects a Subsidy Access Policy's redemption request to allow late enrollments via the `allow_late_enrollment` transaction metadata. When supplied, the subsidy service will in turn request the bulk enrollment request be "forced" via the `force_enrollment` key.
ENT-8525
This is one of three PRs which percolate this single boolean through multiple layers of code, all the way down to the core LMS enrollment API:
1. [YOU ARE HERE] https://github.com/openedx/enterprise-subsidy/pull/219
2. https://github.com/openedx/edx-enterprise/pull/2048
3. https://github.com/openedx/edx-platform/pull/34376
=> feat: pass force_enrollment=True to bulk enrollment when the policy requests it

enterprise_subsidy/apps/content_metadata/api.py, enterprise_subsidy/apps/content_metadata/tests/test_api.py
=> fix: fallback to additional_metadata again to fetch the variant_id

enterprise_subsidy/settings/devstack.py
This pull request updates the Memcache location configuration in the codebase to use an environment variable (MEMCACHE_HOST) with a fallback value.
=> Use env variable for Memcache location

docs/internationalization.rst, enterprise_subsidy/settings/base.py
Ref https://github.com/openedx/edx-documentation/issues/2339
=> docs: Update edx.rtd.io links to docs.openedx.org

enterprise_subsidy/apps/transaction/signals/handlers.py
ENT-10212 | Improves logging around the reversal of revoked LC enrollments.
=> fix: improve logging for non-refundable revocations

enterprise_subsidy/apps/transaction/admin.py
ENT-10271 | The [openedx-ledger base transaction admin](https://github.com/openedx/openedx-ledger/blob/db2c68fa8ac558ed62e929d7c8befbde84b36e44/openedx_ledger/admin.py#L179-L185) has the allow_ledger_modification setting logic backwards. Fixing it here instead of upstream for expedience.
With `ALLOW_LEDGER_MODIFICATION = False`:
Set to True:
=> fix: transaction admin does right thing when allowing ledger changes

enterprise_subsidy/apps/content_metadata/api.py, enterprise_subsidy/apps/fulfillment/api.py, enterprise_subsidy/apps/subsidy/models.py
=> feat: more defensive product source, link geag id to transaction again

CLAUDE.md, docs/architecture_overview.rst
LLM generated, edited, verified, corrected etc. by me.
=> docs: add arch overview doc
