openedx/enterprise-subsidy

- .coveragerc
- .github/workflows/ci.yml
- codecov.yml
**Description:**
Our quality checks have been failing, because we have been running the codecov step when `toxenv == 'quality'`, which is not right - we want coverage to run on _tests_, not _quality_..  This PR adds that to our ci config, updates our coverage configuration to produce a `coverage.xml` file, and also changes our coverage target to 75% (where it's at currently).
> build: include html, xml coverage output

- enterprise_subsidy/settings/base.py
- enterprise_subsidy/urls.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
django-rest-swagger is deprecated, so first I have to change to drf-yasg.  This also fixes the /api-docs/ page which previously used an outdated template which imported other non-existent templates due to django-rest-swagger no longer being maintained.
ENT-6620
> feat: step 1 of setting up an API: Setup swagger docs.

- .gitignore
- docker-compose.yml
- enterprise_subsidy/settings/devstack.py
**Description:** 
Attempting to run enterprise-subsidy on my M1 Apple Silicon machine did not work:
```shell
❯ make dev.up
docker-compose up -d
Creating network "enterprise-subsidy_default" with the default driver
Creating volume "enterprise-subsidy_enterprise_subsidy_mysql" with default driver
Pulling db (mysql:5.6)...
5.6: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
make: *** [dev.up] Error 1
```
Following the fix in other IDAs, I bumped the MySQL version in docker-compose.yml to MySQL8.
Secondarily, when trying to authenticate with enterprise-subsidy for the first time, I got redirected to an error in the LMS with a "invalid client id" warning. There is a mismatch between the client ids in the generated OAuth applications and …
> fix: use mysql8 in docker-compose.yml and ensure social auth key/secret are correct

- docs/decisions/0002-initial-api-specification.rst
- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/urls.py
- enterprise_subsidy/apps/api/v1/views.py
- enterprise_subsidy/apps/subsidy/api.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/factories.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Before this change, POST /api/v1/transactions/ inherits the default create action to create a Transaction.  After this change, it is actually hooked up to the redeem() function which contains the rest of the business logic to redeem a subsidy, aside from just the creation of a Transaction.
ENT-6836
> feat: connect POST /api/v1/transactions/ to redeem()

- .github/PULL_REQUEST_TEMPLATE.md
- enterprise_subsidy/apps/content_metadata/admin.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/apps.py
- enterprise_subsidy/apps/content_metadata/models.py
- enterprise_subsidy/apps/fulfillment/admin.py
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/apps.py
- enterprise_subsidy/apps/fulfillment/constants.py
- enterprise_subsidy/apps/fulfillment/models.py
- enterprise_subsidy/settings/base.py
Adds stubbed/non-functional Django apps for `fulfillment` and `content_metadata`.
Related to https://2u-internal.atlassian.net/browse/ENT-6804
Run the unit tests.
> feat: add stubbed fulfillment and content_metadata apps.

- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/api_client/tests/test_enterprise_catalog.py
- enterprise_subsidy/settings/base.py
- enterprise_subsidy/settings/devstack.py
Added oauth enterprise catalog service oauth client to the service. 
> feat: adding an enterprise catalog oauth client

- enterprise_subsidy/apps/api/v1/tests/mixins.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/utils.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Before this change, anybody with learner or higher permissions on any context could perform any REST operation on transactions not their own. After this change, requesters must explicitly have admin or operator privileges on a given enterprise customer in order to list(), retrieve(), (etc.), transactions that do not have a lms_user_id matching that of the requester.
ENT-6886
> feat: list() and retrieve() transactions with more filtering

- Makefile
Use dashes in container names in the Makefile.
```
make dev.up.build
make app-shell
```
> build: dash, not underscore, in make target container names

- enterprise_subsidy/settings/devstack.py
- provision-enterprise-subsidy.sh
https://github.com/openedx/enterprise-subsidy/pull/31 when updating the container name, we decided to also update the mysql container name. I forgot to update the values for the db container elsewhere in the setup scripts
turn subsidy service on and off again, then make sure things work.
> fix: updating db name to remove underscore

- enterprise_subsidy/apps/api/serializers.py
- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
```
commit 7d3ad74d5b982205dc7ba3fbca03dcd83d9a189e
Author: Troy Sankey <tsankey@edx.org>
Date:   Mon Mar 20 20:15:54 2023 -0400
feat: add transaction query params `content_key`, `learner_id`, `include_aggregates`
ENT-6886
commit f611a8bc35bc8cc54cfe2e6e09359dc4e579ec15
Author: Troy Sankey <tsankey@edx.org>
Date:   Mon Mar 20 17:26:04 2023 -0400
feat: list transactions filtering by subsidy_access_policy_uuid
Also:
* Rename transaction create() API parameter ``access_policy_uuid`` ->
``subsidy_access_policy_uuid`` for better consistency with serialized
response objects.
* Add a missing test ``test_retrieve_invalid_uuid()``
* Fix 500 error when an invalid subsidy_uuid is passed via query_parameter.
ENT-6886
```
> ENT-6886: Various list transactions enhancements

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/subsidy/api.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/rules.py
- enterprise_subsidy/apps/subsidy/signals.py
- enterprise_subsidy/apps/subsidy/tests/__init__.py
- enterprise_subsidy/apps/subsidy/tests/factories.py
- enterprise_subsidy/apps/subsidy/tests/test_api.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
- enterprise_subsidy/apps/subsidy/tests/test_rules.py
- enterprise_subsidy/urls.py
* Adds a `can_redeem` detail action to the `SubsidyViewSet`
* More strongly formalizes what it means to be redeemable.
* Adds unit tests for all the functions that deal with redeemability.
> feat: add subsidy can_redeem action to API

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api_client/tests/test_enterprise.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
https://2u-internal.atlassian.net/browse/ENT-6933
1) adding search bar to subsidy's django admin transaction screen 
2) updated references to transaction reference ID's that are now aligned with the new `platform enrollment ID` and `GEAG allocation ID`
> feat: allowing for admins to search for transactions

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
- requirements/base.txt
- requirements/ci.in
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
This is a followup from openedx_ledger changes in https://github.com/openedx/openedx-ledger/pull/17 to implement locking on the ledger object during transaction creation.
* POST /api/v1/transactions: add a new 429 response to  when the ledger is locked.
* POST /api/v1/transactions: update reponse code to 422 (was 403) when subsidy is not redeemable.
* Add basic model test for Subsidy.redeem(), and additional view tests to cover the above two bullets.
* Also, make sure the Transaction lifecycle fully progressess through either:
- created -> pending -> committed
- created -> pending -> failed
* make upgrade
- remove codecov package from ci.txt
ENT-6835
> feat: Take ledger locking into account

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_api.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
This combo commit combines two unrelated fixes that are too hard to split up into two commits because they both touch the same lines of code:
* On redeem (create transaction) if the requested content_key is not found, the response should be 422 instead of 500.
* Stop double-converting dollars to cents.  Previously, transaction records would be written with quantity values 100x larger than they should have been.
Unticketed work.
> fix: content_key not found should respond with 422, and stop double-converting dollars to cents

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/content_metadata.py
- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/api_client/tests/test_enterprise_catalog.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/constants.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
- enterprise_subsidy/apps/subsidy/constants.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_api.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
- Breaking out some of the work in https://github.com/openedx/enterprise-subsidy/pull/51
- refactor some of the content metadata stuff
- add geag variant id capture
> feat: add geag variant to contentmetadata

- enterprise_subsidy/apps/api/v1/exceptions.py
- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
- enterprise_subsidy/apps/subsidy/constants.py
- enterprise_subsidy/apps/subsidy/rules.py
* POST /api/v1/subsidies/
* DELETE /api/v1/subsidies/{uuid}/
ent-6998
Adds the create and delete endpoint for subsides, using drf-spectacular to document the intended use cases
> feat: add create and delete endpoint for subsidies

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
- Adds the ability to pass metadata into the final transaction.
- https://2u-internal.atlassian.net/browse/ENT-7068
- https://github.com/openedx/enterprise-access/pull/134
> feat: redemption metadata

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/api_client/enterprise.py
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
This is a mostly* no-op change to make the code consistently refer to the user identifier using the same name.
\* = the REST API endpoint to list transactions has been changed to require an "lms_user_id" query parameter instead of "learner_id".  This fixes an integration bug cased by enterprise-access passing "lms_user_id" when it was not accepted.
ENT-6988
Related PRs:
* https://github.com/openedx/enterprise-access/pull/138
* https://github.com/openedx/edx-enterprise-subsidy-client/pull/16
> refactor: `learner_id` -> `lms_user_id`

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
Previously, if a user had the following role:context pairs in their JWT, they would be considered only a learner for the enterprise customer A:
* `enterprise_admin:*`
* `enterprise_learner:<enterprise customer A>`
However, since they have all-access as admin, they should instead be considered an admin for the enterprise customer A.
> fix: all access admins can always list all transactions

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
Threads `metadata` through to the `redeem()` call, so that we can support e.g. GEAG fulfillment.
also removes use of lru_cache from Subsidy.price_for_content() method, because
we're unsure how it actually "works"
> feat: v2 transaction create API now supports metadata field input

- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/tests/test_api.py
- geag needs an email address and data share consent
- we'll have the frontend pass both (rather than look it up)
> fix: pass email and data consent to geag

- enterprise_subsidy/apps/api/v1/views/content_metadata.py
- enterprise_subsidy/settings/base.py
https://2u-internal.atlassian.net/browse/ENT-7135
We actually already have a per-view cache decorator on the content-metadata GET handler.
[Django](https://docs.djangoproject.com/en/3.2/topics/cache/#the-per-view-cache)   It’s currently set to cache for 60 seconds.  As the docs note: “Additionally, cache_page automatically sets Cache-Control and Expires headers in the response which affect [downstream caches](https://docs.djangoproject.com/en/3.2/topics/cache/#downstream-caches).”
This PR makes us accept a settings variable to control the timeout of the cache.  This will allow us to tune higher for performance, or to disable it as needed by setting the timeout to 0.
> feat: control content-metadata cache timeout from settings.

- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/tests/test_api.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
- grab enterprise customer data, extract `auth_org_id`
- pipe `auth_org_id` into geag enterprise allocation call
- profit
- https://2u-internal.atlassian.net/browse/ENT-7079
> feat: include auth_org_id in geag allocation

- enterprise_subsidy/settings/devstack.py
Adds the localhost port for frontend-app-support-tools to the devstack `CORS_ORIGIN_WHITELIST`.
> feat: adds support tools localhost to devstack cors whitelist

- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
Uses `product_source`'s `slug` instead of `name`, as the `name` field should be assumed to be changed at any time, although name and slug are currently identical on stage/prod.
> fix: use product source slug

- enterprise_subsidy/apps/api/v1/views/content_metadata.py
- enterprise_subsidy/apps/content_metadata/api.py
> fix: get_course_run() should early return if the content data is a course run

- docs/decisions/0006-transaction-api-state-filtering.rst
- enterprise_subsidy/apps/api/filters.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- enterprise_subsidy/apps/fulfillment/api.py
https://2u-internal.atlassian.net/browse/ENT-7178
With this change, the v2 transaction endpoint will:
* allow for filtering by multiple, OR’d values, e.g. `state=committed&state=failed` should return transactions in either the committed or failed state.
* default to returning otherwise-matching transactions in any state. (i.e. the current behavior)
> feat: allow transaction view to be filtered by state. ENT-7178

- enterprise_subsidy/apps/subsidy/models.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
https://github.com/openedx/openedx-ledger/releases/tag/0.4.0 to get only non-failed transactions to count toward the subsidy balance calculation.
> feat: upgrade edx-rest-api-client and openedx-ledger

- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
We started running into “Incorrect padding” JWT errors after upgrading to edx-drf-extensions 8.8.0.
This pins edx-drf-extensions<8.8, reintroducing pyjwkest
> build: constraint edx-drf-extensions<8.8

- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
This reverts commit 02443266b921612b960ea22e1998c50ca7f7151e.
We've got a config change we think fixes the original issue.
> Revert "build: constraint edx-drf-extensions<8.8"

- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
- enterprise_subsidy/apps/core/tests/test_utils.py
- enterprise_subsidy/apps/core/utils.py
Stores content metadata payload in the request cache, which should mean that we make at most one call per content key to enterprise-catalog from the enterprise-subsidy per `can_redeem` request.
* Run `make app-logs | grep enterprise-catalog` to tail the logs
* Make a request to `can_redeem`, either via enterprise-access, or directly against enterprise-subsidy
* Watch for only 1 request to enterprise-catalog
* Do this outside of this branch to notice that there are two such requests.
> feat: use request cache to store content metadata results.

- enterprise_subsidy/__init__.py
- enterprise_subsidy/apps/api/exceptions.py
- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- enterprise_subsidy/apps/subsidy/models.py
Most error responses will now contain a JSON dict with 'detail' and 'code' keys, and result in a 422 response code when redemption could not occur. ENT-7132
https://2u-internal.atlassian.net/browse/ENT-7132
> feat: admin transaction create returns more structured error detail

- docker-compose.yml
- enterprise_subsidy/settings/devstack.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
* Configure devstack settings to use memcached container
* install pymemcache package
* run memcache container on devstack default network
After this change/testing instructions:
```
./manage.py shell_plus
[...]
(InteractiveConsole)
>>> cache.get('go')
>>> cache.set('go', 2)
>>> cache.get('go')
2
>>> settings.CACHES
{'default': {'BACKEND': 'django.core.cache.backends.memcached.PyMemcacheCache', 'LOCATION': 'enterprise-subsidy.memcache:11211'}}
```
> feat: memcached config for devstack, install pymemcache

- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/tests/test_api.py
- GEAG/Titan now supports 36 char payment reference ids
- We had been truncating our our reference id to 20 char previously
- https://2u-internal.atlassian.net/browse/ENT-7143
> feat: send full transaction uuid to geag

- enterprise_subsidy/apps/subsidy/api.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_api.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
tl;dr; When redeeming a policy/subsidy for a course run that had been previously redeemed and then had the associated transaction and enrollment reversed, we don't allow the learner to redeem the course again but treat it as a success. The reason is that we see a committed transaction but don't take into the account the fact that it was reversed. So, we don't attempt redemption again when we should, so the learner's enrollment stays inactive.
1. Redeem a subsidy for some content by clicking the "Enroll" CTA on the course page and get redirected to courseware.
2. Return to course page and see "View course" button indicating existing enrollment.
3. Refund & unenroll the learner.
4. Observe that `CourseEnrollment.is_active=False` and the "Enroll" CTA returns on the course page.
5. Click the …
> fix: ensure new transactions to enroll in previously unenrolled courses flips the enrollment to active

- Dockerfile
- Makefile
- docker-compose.yml
This helps avoid the `django-debug-toolbar` not installed errors we all face when re-building/re-starting our subsidy containers on devstack.  It creates a new image tag called `latest-devstack` and uses that image by default in `docker-compose.yml`.  Within this tag, we install the dev requirements, so that django-debug-toolbar can be installed during our devstack build, which means it's always there as soon as the container starts.
(I copied this solution from enterprise-access)
```
make dev.down
make dev.up.build-no-cache
make app-shell
```
> build: new devstack-specific tagged image with dev requirements

- enterprise_subsidy/settings/devstack.py
Add `frontend-app-admin-portal` to the CORS allowlist in devstack.
> chore: add frontend-app-admin-portal to CORS allowlist

- enterprise_subsidy/apps/api_client/enterprise.py
A recent PR in edx-enterprise: https://github.com/openedx/edx-enterprise/pull/1763 corrected the spelling of "fulfillment", which we return in the response payload of our bulk enrollment API calls to enterprise-subsidy.
Unfortunately, we had previously copied the mis-spelled key name as a constant into enterprise-subsidy.  This PR corrects that spelling.
https://2u-internal.atlassian.net/browse/ENT-7231
If you're scoring at home - 
copypasta: 1
developers: 0
> fix: put the first 'l' in fulfillment

- enterprise_subsidy/apps/api/exceptions.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- enterprise_subsidy/apps/core/utils.py
- enterprise_subsidy/apps/subsidy/models.py
Check that the subsidy is "current" before creating any transactions via the V2 transactions admin creation view.
* Make a request against `http://localhost:18280/api/v2/subsidies/[a subsidy uuid]/admin/transactions/` after having changed your subsidy's active or expiration time via django admin.
> fix: disallow transaction creation for inactive subsidies

- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
- enterprise_subsidy/apps/core/utils.py
Updates the ContentMetadataApi.get_content_metadata() method to use a TieredCache instead of a request cache. Uses a cache timeout that can be optionally overridden in settings, but defaults to 30 minutes if the setting is not present. 
https://2u-internal.atlassian.net/browse/ENT-7228
Hit the content-metadata API endpoint with two repeated calls with the same inputs, second should be faster.
> feat: ContentMetadataApi.get_content_metadata uses TieredCache now

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- enterprise_subsidy/apps/subsidy/api.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_api.py
By returning a full list of transactions, enterprise-access can generate a versioned idempotency key which takes historical redemptions into account, allowing the learner to re-redeem the same content even after unenrolling+revoking.
ENT-7204
All related PRs:
* https://github.com/openedx/enterprise-access/pull/191
* https://github.com/openedx/enterprise-subsidy/pull/113
* https://github.com/openedx/edx-enterprise-subsidy-client/pull/23
> feat: can_redeem - return full list of transactions

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
Add `is_active field` to  the `Subsidy` API read view
> chore: add is_active field to subsidy API read view

- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/subsidy/admin.py
- enterprise_subsidy/apps/transaction/admin.py
- enterprise_subsidy/settings/base.py
We've had djangoql installed in enterprise-subsidy for a while, but it's been unused.  I incorporated it into the Subsidy and Transaction models in a way that makes its use optional in a given search.
https://github.com/ivelum/djangoql#using-djangoql-with-the-standard-django-admin-search
Check out e.g. http://localhost:18280/admin/subsidy/subsidy/ after pulling this branch
> feat: use djangoql in admin search

- enterprise_subsidy/apps/core/tests/test_utils.py
- enterprise_subsidy/apps/core/utils.py
Same idea as https://github.com/openedx/enterprise-access/pull/196
Hit can-redeem or redeem, you'll get a cache miss the first time, should get a cache hit the second time.  use `make app-logs | grep CACHE` to filter for the cache logging.
> feat: hash the cache key to stay under max memcached length

- .gitignore
- enterprise_subsidy/apps/api/exceptions.py
- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/tests/test_api.py
- enterprise_subsidy/settings/test.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- requirements/validation.txt
Include fulfillment error messages in transaction creation error response payload.
https://2u-internal.atlassian.net/browse/ENT-7271
I'm relying on unit tests for local development, we can test in stage by trying to fulfill a GEAG course twice for the same user, before/after switching them to subsidy-based learner credit.  We could also test by trying to fulfill something with a mismatched variant id.
> feat: return fulfillment error payload in transaction creation response

- docs/how_to/clear_cache.rst
- enterprise_subsidy/settings/base.py
- enterprise_subsidy/urls.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
This PR adds the ability to clear cache from the django admin screen similar to enterprise-catalog. Very useful for QAing data that may be cached and need to be updated real time (e.g. varient_id)
> feat: clear cache option added to django admin

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
* API before: the output-serialized reversal metadata key pointed to a string value containing JSON
* API after: the output-serialized reversal metadata key pointed to a nested JSON dictionary.
redoc before:
redoc after:
> fix: Reversal.metadata field is not correctly serialized

- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
we're seeing the follow logs when attempting to unenroll
```
2023-06-14 12:34:54,863 INFO 1 [enterprise_subsidy.apps.transaction.management.commands.write_reversals_from_enterprise_unenrollments] [user None] [ip None] [request_id None] write_reversals_from_enterprise_unenrollments.py:212 - Updating and writing Transaction Reversals from recent Enterprise unenrollments data
2023-06-14 12:34:55,270 INFO 1 [enterprise_subsidy.apps.transaction.management.commands.write_reversals_from_enterprise_unenrollments] [user None] [ip None] [request_id None] write_reversals_from_enterprise_unenrollments.py:217 - Found 1 recent Enterprise unenrollments
2023-06-14 12:34:55,381 INFO 1 [enterprise_subsidy.apps.transaction.management.commands.write_reversals_from_enterprise_unenrollments] [user None] [ip …
```
> fix: properly parsing datetime strings with decimals seconds

- enterprise_subsidy/settings/base.py
- enterprise_subsidy/urls.py
Update api-docs endpoint to point to `SpectacularSwaggerView` view. 
> fix: update 'api-docs/' endpoint

- enterprise_subsidy/apps/api/paginators.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/utils.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
Adds support for filtering and sorting of subsidies.
Adds `page_count` on paginated data. 
Allows for `page_size` query parameter
Added to support this [ticket](https://2u-internal.atlassian.net/browse/ENT-6942) and [PR](https://github.com/openedx/frontend-app-support-tools/pull/343)
Tests are WIP
> feat: Adds support for filter and sort to Subsidy API

- enterprise_subsidy/apps/api/paginators.py
Updates logic of the `SubsidyListPaginator` to correctly reference the correct Subsidy response object data. 
Split logic to validate a query parameter exist for `page_size` when assigning the paginator value. 
> fix: Update subsidy paginator logic to reference response object

- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- enterprise_subsidy/apps/transaction/views.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
If a transaction is not in a COMMITTED state, it should not allow unenrolls or reversals. This PR only changes the management system. It would be a corner case for a transaction linked to an enrollment object to be anything but COMMITTED, but this should help if a corner case is encountered.
> chore: only allow course unenrollment if transaction is committed

- enterprise_subsidy/apps/content_metadata/api.py
Stop logging cache keys that we can't do anything with.
> fix: don't log useless/opaque cache keys

- Makefile
- docker-compose.yml
- enterprise_subsidy/settings/devstack.py
Switch to mysql 8 for devstack development.
```
make dev.up
make dev.dbcopy8
make app-restart
```
Then login to the admin site to ensure your data was copied: http://localhost:18280/admin/ 
Note that the new mysql 8 container is running side-by-side with mysql 5.7 for now.  For mysql 8, the container's 3306 port is bound to the host's 3406 port, so use 3406 if you use a mysql IDE or something locally.
> build: switch to mysql 8

- docker-compose.yml
Doing so caused conflicts when other services (e.g. enterprise-access) tried to do the same thing.
> build: don't bind 3406 to the host for mysql

- .github/workflows/pypi-publish.yml
Update publish workflow to point away from master and to the documentation's stated branch 
https://github.com/pypa/gh-action-pypi-publish
Other related PRs:
https://github.com/openedx/edx-enterprise/pull/1835
https://github.com/openedx/edx-enterprise-data/pull/386
https://github.com/openedx/openedx-ledger/pull/32
https://github.com/openedx/edx-rest-api-client/pull/288
https://github.com/openedx/ecommerce-worker/pull/205
https://github.com/openedx/edx-rbac/pull/247
https://github.com/openedx/edx-analytics-data-api-client/pull/135
https://github.com/edx/braze-client/pull/16
> feat: update pypa's publish branch away from master

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/content_metadata/api.py
This is in support of associating `content_title` with assignments. Since `content_title` is something akin to a "human-readable id" we're okay with adding this to the summary (versus making a new, direct call into the catalog service from access).
- https://2u-internal.atlassian.net/browse/ENT-7866
> feat: add content_title to metadata summary api

- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
We're doing many small selects of related reversals and external references in our transaction list APIs.  This PR selects/prefetches the related records.  This should provide a moderate improvement in performance of these APIs.
TODO
> perf: select_related and prefetch_related in transactions APIs

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/content_metadata.py
- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/settings/base.py
Include the `skip_customer_fetch` param on calls to fetch customer content metadata. See https://github.com/openedx/enterprise-catalog/pull/702
> feat: skip customer fetch in content_metadata view

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_api.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
Use a clean method to validate that non-internal-only subsidies must be unique on (reference_id, reference_type), since mysql does not support conditional unique constraints. ENT-7891
> fix: validate subsidy uniqueness with clean() method.

- .github/workflows/upgrade-python-requirements.yml
Description:
Currently upgrade automation is failing as it's trying to pull from a `master` branch but that doesn't exist in this repo. I've switch this to `main` as it does not seem that the automation is picking up the variable from the job execution.
Cribbed from here: https://github.com/openedx/edx-analytics-dashboard/blob/2e7b2dc8ad07d8d133ee9d008ce479dd4121bd9b/.github/workflows/upgrade-python-requirements.yml#L14
> chore: fix upgrade requirements github action

- enterprise_subsidy/apps/api/schema.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/content_metadata.py
ENT-7788
Ticket with context: https://2u-internal.atlassian.net/browse/ENT-7788
> noticed that it looks like ContentMetadataViewSet in enterprise-subsidy throws a 500 when it's called without the enterprise_customer_uuid query parameter
I was unable to reproduce this issue, as the response was 403 when no parameter was supplied (and supplying the parameter returns a 200).  For completeness, I added a unit test to make sure the response is 403.
> test: add test for content-metdata retrieve without customer query param

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api_client/lms_user.py
- enterprise_subsidy/apps/api_client/tests/test_lms_user.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
- enterprise_subsidy/settings/base.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
- populates `lms_user_email` and `content_title` on new `Transactions`
- i will follow with a management command to back-fill existing transaction data later
- https://2u-internal.atlassian.net/browse/ENT-7867
- https://2u-internal.atlassian.net/browse/ENT-7868
> feat: additional Transaction fields

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- DRF search on Transactions list
- search fields include learner email address and content title
- https://2u-internal.atlassian.net/browse/ENT-7683
> feat: search transactions by learner email and content title

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/views/transaction.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- adds an `ordering` query param which supports `created` and `quantity`
- https://2u-internal.atlassian.net/browse/ENT-7952
> feat: transaction api ordering

- enterprise_subsidy/settings/devstack.py
Adds CSRF_TRUSTED_ORIGIN to the devstack setting to overcome a local development issue that appeared in the support tools repository when provisioning new subsidies/policies.
Preemptively added the learner portal and admin portal local development endpoints to have the trusted origins list match the whitelist. 
> fix: Adds CSRF trusted origin to devstack settings

- enterprise_subsidy/apps/transaction/management/commands/backpopulate_transaction_email_and_title.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- enterprise_subsidy/apps/transaction/utils.py
- backpopulate `lms_user_email` and `content_title` for `Transactions`
- https://2u-internal.atlassian.net/browse/ENT-7974
- based on work done in https://github.com/openedx/enterprise-subsidy/pull/162
> feat: backpopulate transaction email and content title

- enterprise_subsidy/apps/transaction/management/commands/backpopulate_transaction_email_and_title.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- properly handles situations where transactions don't have an `lms_user_id` or `content_key`
- https://2u-internal.atlassian.net/browse/ENT-7974
- https://github.com/openedx/enterprise-subsidy/pull/181
> feat: improve backpopulate job specificity

- enterprise_subsidy/apps/transaction/management/commands/backpopulate_transaction_email_and_title.py
- follow-on to https://github.com/openedx/enterprise-subsidy/pull/182
- make task a bit more robust, able to continue due to individual record issues
- eg observed issues looking up course content titles in catalogs which have changed
> fix: adding exception handling

- enterprise_subsidy/apps/api/paginators.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
https://2u-internal.atlassian.net/browse/ENT-8106
Ensure the enterprise-subsidy transactions list API utilizes the DefaultPagination class from edx-drf-extensions.
Unit tests
> feat: adhering transaction api list view to edx rest framework default pagination

- docker-compose.yml
Removes mysql 5.7 container and volume from dev environment.
> build: no more mysql 5.7

- enterprise_subsidy/apps/core/utils.py
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/tests/test_api.py
> ENT-8079 - Make DSC optional based on enterprise config

- enterprise_subsidy/apps/subsidy/admin.py
- enterprise_subsidy/apps/transaction/admin.py
* DjangoQL off by default in Subsidy, Ledger, and Transaction
* Add an inline to the related subsidy.
* EC uuid and ledger uuid in the list display
* Searchable by ledger and EC uuids.
* Add EC uuid to edit view
> feat: some transaction, subsidy, and ledger django admin improvements

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/api_client/tests/test_enterprise_catalog.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/settings/base.py
Right now all of our enterprise catalog content metadata API client methods are depending on customer because the catalog service only surfaced content through a customer's context. This was too rigid for our purposes in the transaction reversal procedure where we needed to query for the course start date regardless of whether or not the content belonged under the customer's catalog. I've updated the catalog service to surface content metadata records without tying the serializer to the customer, so that the subsidy service can query and find the information it needs without having the association between content and customer catalog.
> feat: adding a non-customer dependent content metadata api client

- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
If the subsidy service requests non customer specific content metadata for a course run, it will only get metadata on that course run (not the parent course). This adds the flexibility to not assume the content metadata is of content_type course 
> fix: accounting for content type of metadata when writing transaction reversals

- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/api_client/tests/test_enterprise_catalog.py
> fix: pulling results out of the response payload from the catalog service for content metadata

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
**Background**: There's an internal helper method to generate "summary" data for a piece of content, which is used all over this codebase to extract relevant bits of metadata from said content. The summary data is also used verbatim in the enterprise-subsidy content metadata API endpoint (`/api/v1/content-metadata/<content-identifier>/`). The problem was that this helper method relied on `additional_metadata` from the content metadata, but that dict is now deprecated.  Furthermore, when a course RUN key was passed to this helper method, the result would incorrectly include the variant_id of the advertised run, potentially a different run than request.
**This PR**: Change logic to actually fetch the `variant_id` of the requested course run, and fallback to that of the advertised course …
> fix: correct variant is included in summary data for content

- .github/workflows/ci.yml
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/transaction/api.py
- enterprise_subsidy/apps/transaction/apps.py
- enterprise_subsidy/apps/transaction/exceptions.py
- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/apps/transaction/signals/handlers.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- enterprise_subsidy/apps/transaction/tests/test_signal_handlers.py
- enterprise_subsidy/apps/transaction/tests/test_views.py
- enterprise_subsidy/apps/transaction/views.py
Encapsulates logic around canceling _platform_ fulfillment/enrollment, external fulfillment (e.g. GEAG), and transaction reversal into a new `transaction.api` module. Then refactors and/or modifies three main integration points to make use of this new module as follows:
1. The reversal-writing management command now calls the common business logic functions to cancel _external_ fulfillments before reversing a transaction. This is just a refactor, no new behavior here.
2. Modified the `listen_for_transaction_reversal` signal handler to cancel both external (GEAG) and platform fulfillments. New behavior here is to cancel the external fulfillment. For background, this signal handler is what enables the "Unenroll & Refund" Transaction Django Admin action to perform the "unenroll" portion.
3. …
> feat: unfulfillment logic consolidation

- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/transaction/api.py
1. Adds logging for when we successfully fulfill or un-fulfill a transaction.
2. Cleans up some extraneous logging.
3. Converts some logging from `info` to `error` (because those calls are in an error condition).
> feat: add fulfillment logging, clean up misc logging

- enterprise_subsidy/apps/api/schema.py
- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v1/urls.py
- enterprise_subsidy/apps/api/v1/views/content_metadata.py
- enterprise_subsidy/apps/api/v1/views/subsidy.py
- enterprise_subsidy/apps/subsidy/models.py
https://2u-internal.atlassian.net/browse/ENT-8562
first of two steps. First expose aggregated enrollment data pertaining to particular subsidies from enterprise-subsidy via a new API endpoint. Then have access query and cache said new endpoint, requesting pages of enterprise group member data and zipping the data together to form a hydrated enterprise group members view.
run unit tests, alternatively hit `http://localhost:18280/api/v1/subsidies/<subsidy-UUID>/aggregated-enrollments` after fetching and running locally
> feat: adding api subsidy endpoint to surface aggregated subsidy enrollment data

- openedx.yaml
This repo has been "maybe" for a while, but it has not been tagged yet. I propose that we remove the "maybe" and simply do not tag it. My reasoning is that it is not clear from the README or the ADRs how this microservice could be used by an Open edX site operator.
According to [OEP-10](https://docs.openedx.org/projects/openedx-proposals/en/latest/processes/oep-0010-proc-openedx-releases.html#levels-of-support): 
> To be included in an Open edX release, a component must meet these criteria.
> * It must be successfully merged into its repository’s release-from branch. This is typically master, though it can be any branch.
> * It must be installable in at least one of the supported installation methods.
> * It must be usable in the installed configuration.
This decision can always be …
> build: do not tag this in the named open edx release

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/subsidy/models.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Aggregates all adjustments and the subsidy `starting_balance` into a net new field labeled `total_deposits` within the Subsidy model as a computed field.
> feat: Create and serialize total_deposits field

- requirements/base.txt
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Notably installs https://github.com/openedx/openedx-ledger/releases/tag/1.4.4 to make the `Reversal` Django admin class set `transaction` as an autocomplete field, so we can more easily create reversal records.
Ran `make upgrade`, so other deps are also upgraded.
> feat: upgrades deps, including openedx-ledger=1.4.4

- requirements/base.txt
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
https://github.com/openedx/openedx-events/releases/tag/v9.11.0
Includes new enterprise signals and data classes for `Transaction` events.
> feat: upgrade openedx-events to 9.11, plus other upgrades

- Makefile
When trying to deploy enterprise-subsidy using a Ansible playbook based on the edx_django_service role - https://github.com/openedx/configuration/pull/7107, the production requirements fail to install as the pip-tools are missing. This commit makes installing pip-tools a prereq for install production-requirements.
Running `make production-requirements` after a fresh clone completes without fail.
> build: make pip_requirements a prereq for production-requirements

- docker-compose.yml
also deletes deprecated `version` key from `docker-compose.yml`
> build: use a modern memcached image

- enterprise_subsidy/apps/core/event_bus.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/transaction/api.py
- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/apps/transaction/signals/handlers.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- enterprise_subsidy/apps/transaction/tests/test_signal_handlers.py
- enterprise_subsidy/settings/base.py
- enterprise_subsidy/settings/devstack.py
- enterprise_subsidy/settings/test.py
- requirements/base.in
Emit openedx events (to the event bus) when transactions are created, committed, failed, and reversed.
Additionally fixes a bug in the write-reversals mgmt command that proceeded to write a reversal in case an external fulfillment could not successfully be canceled.
ENT-8761
ENT-9009
See proposed consumption: https://github.com/openedx/enterprise-access/pull/502
0. Run `make app-logs` in enterprise-subsidy, or have the local kafka control center running in your browser.
1. Find a combination of (policy, learner, content key) that can be redeemed.
2. Hit the policy redeem endpoint.
3. The response should be a committed transaction, and you should see events emitted to kafka in your logs.
From enterprise-subsidy:
```
enterprise-subsidy.app  | 2024-06-26 14:02:32,049 DEBUG 129 …
```
> feat: emit transaction lifecycle events

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/subsidy/migration_utils.py
- enterprise_subsidy/apps/subsidy/migrations/0022_backfill_initial_deposits.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/signals.py
- enterprise_subsidy/apps/subsidy/tests/test_migration_utils.py
- enterprise_subsidy/apps/subsidy/tests/test_migrations.py
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- requirements/validation.txt
This needs to be located in the Subsidy app instead of openedx_ledger because it relies on having access to the SubsidyReferenceChoices class.
ENT-9075
BLOCKED on https://github.com/openedx/openedx-ledger/pull/96
BLOCKED on https://github.com/openedx/openedx-ledger/pull/97
> feat: Add data migration to backfill legacy initial deposits

- enterprise_subsidy/apps/subsidy/migrations/0022_backfill_initial_deposits.py
- enterprise_subsidy/apps/subsidy/tests/test_migrations.py
> fix: make initial deposit backfill defensive against subsidy-less ledgers

- enterprise_subsidy/apps/subsidy/migrations/0022_backfill_initial_deposits.py
- enterprise_subsidy/apps/subsidy/tests/test_migrations.py
ENT-9075
This is safe (i.e. no meaningful data loss) in both stage and prod because we only ever used opportunity_product_id for an internal subsidy.
stage:
```
mysql> select reference_type, internal_only, max(created), count(*) from subsidy_subsidy group by reference_type, internal_only;
+----------------------------------+---------------+----------------------------+----------+
| reference_type                   | internal_only | max(created)               | count(*) |
+----------------------------------+---------------+----------------------------+----------+
| salesforce_opportunity_line_item |             0 | 2024-04-08 15:23:46.105183 |       11 |
| salesforce_opportunity_line_item |             1 | 2024-06-17 13:40:43.371173 |      148 |
| opportunity_product_id           | …
```
> fix: make deposit backfill migration defensive against bogus subsidy reference type

- enterprise_subsidy/apps/api/exceptions.py
- enterprise_subsidy/apps/api/v2/serializers/deposits.py
- enterprise_subsidy/apps/api/v2/tests/test_deposit_views.py
- enterprise_subsidy/apps/api/v2/tests/test_serializers.py
- enterprise_subsidy/apps/api/v2/urls.py
- enterprise_subsidy/apps/api/v2/views/deposit.py
- enterprise_subsidy/apps/api/v2/views/transaction.py
- enterprise_subsidy/apps/subsidy/constants.py
- enterprise_subsidy/apps/subsidy/rules.py
- enterprise_subsidy/apps/subsidy/tests/factories.py
> feat: add API endpoint to create deposits

- enterprise_subsidy/apps/api/v2/serializers/deposits.py
- enterprise_subsidy/apps/api/v2/tests/test_deposit_views.py
Treat null as just no metadata.
ENT-9133
> fix: null metadata should just be tolerated

- enterprise_subsidy/settings/production.py
By adding the variable in production, we are making sure that the "next" variable that shows up when an API response is paginated defaults to HTTPS instead of HTTP. 
[More information in the Jira ticket. ](https://2u-internal.atlassian.net/browse/ENT-9225)
> fix: correcting next var in pagination

- requirements/base.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Installs https://github.com/openedx/openedx-ledger/pull/107
> fix: openedx-ledger to 1.5.6

- requirements/base.txt
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
We had pinned DRF because version 3.15.0 was problematic/non-backwards-compatible. That's been fixed in DRF >= 3.15.1
> build: unpin DRF

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
Since we *always* have a course run within the scope of `summary_data_for_content()` executions, the enroll by date should always be determined directly from a course run record, and not from the *course's* `normalized_metadata` dictionary (the latter of which will always contain the advertised run's enrollment deadline, regardless of the *requested* course run - we typically request course runs, and not courses, of this endpoint in prod). 
ENT-7472
The enterprise-subsidy CM endpoint calls the catalog customer CM endpoint.  If you pass the latter (catalog-customer-cm endpoint) a course run, you'll typically get a top-level _course_ back, with course runs inside of it. So despite typically receiving runs as input to the subsidy CM API, within the bounds of `summary_data_for_content()`, …
> fix: content_metadata enroll_by_date only drawn from course runs.

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/constants.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
ENT-8786
* Price for content now handles the "exceptional" case (a twou EE course) first.
* All content prices now default to 0.0 if their value would otherwise be null/falsey.
> fix: compute price more defensively

- enterprise_subsidy/apps/api/v1/serializers.py
- enterprise_subsidy/apps/api/v1/tests/test_views.py
https://2u-internal.atlassian.net/browse/ENT-9498
1. Add a subsidy to http://localhost:18280/admin/subsidy/subsidy/
2. check that the api response from the subsidy you just created returns "created" http://localhost:18280/api/v1/subsidies/?enterprise_customer_uuid=<enterprise_customer_uuid>
> feat: add created date to subsidy serializer

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
The `price_for_content` logic updated to look for the net new field `normalized_metadata_by_run` which is included as part of these series of PRs.
https://github.com/openedx/enterprise-catalog/pull/930
https://github.com/openedx/enterprise-catalog/pull/931
> feat: retrieve content_price from normalized_metadata_by_run

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api_client/enterprise_catalog.py
- enterprise_subsidy/apps/content_metadata/api.py
- enterprise_subsidy/apps/content_metadata/tests/test_api.py
> feat: update get_content_metadata_for_customer to use v2 endpoint

- Makefile
- requirements/base.txt
- requirements/common_constraints.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Pins confluent-kafka < 2.7, since we're experiencing increased CPU usage in stage and prod with 2.7.0 installed.
> build: pin confluent-kafka<2.7

- README.rst
Minor docs change to force a new deployment.
> docs: fix typo in readme

- enterprise_subsidy/apps/transaction/signals/handlers.py
- enterprise_subsidy/apps/transaction/tests/test_signal_handlers.py
- enterprise_subsidy/apps/transaction/utils.py
At some point during initial development I assumed the serialized data objects from openedx_events supported dict-like access patterns. I was wrong. This commit generalizes access patterns to support both dicts and objects so that we can continue to support both event-driven and cron-driven reversal writing.
> fix: add data object serialization support for reversal writing

- enterprise_subsidy/apps/transaction/tests/test_utils.py
- enterprise_subsidy/apps/transaction/utils.py
In all of our current code that I'm aware of, we only ever pass a course run to unenrollment_can_be_refunded(), but I left a bug in the case where we pass a course.  I'm not completely sure if we need to support this branch anymore, but as long as its there we shouldn't leave it broken.
> fix: coerce CourseLocator to str also when checking refundability given a course

- docker-compose.yml
Launching the new container:
```
(enterprise-subsidy) ubuntu@ip-10-13-20-242:~/edx-repos/enterprise-subsidy$ make dev.up
docker-compose -f /home/ubuntu/edx-repos/devstack/docker-compose.yml up -d redis
[+] Running 1/0
✔ Container edx.devstack.redis  Running                                                                                                                                                                                        0.0s 
docker-compose up -d
[+] Running 4/4
✔ Container enterprise-subsidy.memcache                                            Running                                                                                                                                     0.0s 
✔ Container enterprise-subsidy.mysql80 …
```
> test: add local dev container for consuming event-bus events

- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/apps/transaction/signals/handlers.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- enterprise_subsidy/apps/transaction/tests/test_utils.py
- enterprise_subsidy/apps/transaction/utils.py
Our refundability logic currently uses the course enrollment record’s creation time as the anchor point for determining if we’re inside the refund eligibility window.  However, this doesn’t work out in cases where a learner has enrolled, unenrolled, and re-enrolled later, because we keep at most one course enrollment record per (learner, course).  In this case, our current logic would look too far back (at the original enrollment datetime).  Instead, refundability logic should look at the latest committed transaction’s creation date when determining if we’re inside the eligibility window. ENT-10224
> fix: refundability anchors to transaciton creation time

- enterprise_subsidy/settings/base.py
- enterprise_subsidy/settings/local.py
- enterprise_subsidy/settings/production.py
- enterprise_subsidy/settings/utils.py
Allow logging format to be overridden via LOGGING_FORMAT_STRING.
ENT-10092
> chore: Allow logging format to be overridden

- enterprise_subsidy/settings/production.py
This will allow certain environment-specific headers (such as Datadog-specific headers) to be allowed without polluting this generic codebase.
ENT-9625
> feat: Support injection of extra allowed headers

- requirements/base.txt
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Runs `make upgrade` to upgrade `getsmarter-api-clients` to the latest version ([0.6.2](https://github.com/edx/getsmarter-api-clients/releases/tag/0.6.2)) to add additional logging of the payload sent to GEAG during allocation.
> chore: upgrade requirements to pull in latest getsmarter-api-clients (0.6.2)

- enterprise_subsidy/apps/transaction/api.py
- enterprise_subsidy/apps/transaction/management/commands/write_reversals_from_enterprise_unenrollments.py
- enterprise_subsidy/apps/transaction/signals/handlers.py
- enterprise_subsidy/apps/transaction/tests/test_management.py
- enterprise_subsidy/apps/transaction/tests/test_signal_handlers.py
- enterprise_subsidy/apps/transaction/utils.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/production.txt
- requirements/quality.txt
- requirements/test.txt
- requirements/validation.txt
Cancel external fulfillments when the internal one was canceled, regardless of whether the money can be refunded.
Also, refactor the code to make it more DRY across signal handlers and cron-invoked management commands.
ENT-10284
> fix: make external unenrollment insensitive to refundability

- enterprise_subsidy/apps/transaction/admin.py
ENT-10488
* Deposits and Adjustments are searchable, especially via ledger/subsidy UUID.
* Use DjangoQL, but default to off.
* Standard searchable fields: uuid, ledger.subsidy.uuid, ledger.subsidy.customer_uuid, opp id.
> feat: improved deposit and adjustment admin classes

- enterprise_subsidy/apps/api/exceptions.py
- enterprise_subsidy/apps/api/v2/tests/test_deposit_views.py
- enterprise_subsidy/apps/api/v2/views/deposit.py
Allow for the creation of deposits as long as the related subsidy has not yet expired, even if the subsidy/ledger is not yet *active*.
ENT-10615
Testing:
Hit this endpoint on a subsidy that has already expired:
```
curl --location 'http://localhost:18280/api/v2/subsidies/4025047c-609a-4e64-8546-aaddb15af4eb/admin/deposits/' \
--header 'Authorization: JWT [your-jwt]
--header 'Content-Type: application/json' \
--data '{does not actually matter for this test}'
}'
```
> fix: create deposit api view less restrictive

- enterprise_subsidy/apps/api/v1/tests/test_views.py
- enterprise_subsidy/apps/api/v2/tests/test_transaction_views.py
- enterprise_subsidy/apps/fulfillment/api.py
- enterprise_subsidy/apps/fulfillment/tests/test_api.py
- enterprise_subsidy/apps/subsidy/models.py
- enterprise_subsidy/apps/subsidy/tests/test_models.py
Fixes a case where:
1. we're redeeming an exec ed transaction.
2. there's no variant id available for the content we're redeeming
This resulted in us gracefully skipping over external fulfillment, but still continuing with the edx enrollment and the transaction being committed.
I've only tested via unit tests so far.
> fix: check if we're doing a geag fulfillment *and* have a variant id
